# Generated by Django 4.2.8 on 2026-01-07 16:15

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_resized.forms
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BibleVerse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verse', models.TextField()),
                ('reference', models.CharField(max_length=100)),
                ('display_date', models.DateField(default=django.utils.timezone.now)),
                ('display_on_homepage', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-display_date'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('read', 'Read'), ('replied', 'Replied'), ('archived', 'Archived')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('color', models.CharField(default='#3498db', max_length=7)),
                ('icon', models.CharField(default='fas fa-calendar', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Event Categories',
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', help_text='Image size: 1200x800 pixels', keep_meta=True, quality=85, scale=None, size=[1200, 800], upload_to='gallery/')),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=300)),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', help_text='Recommended size: 1920x1080 pixels', keep_meta=True, quality=85, scale=None, size=[1920, 1080], upload_to='hero/')),
                ('button1_text', models.CharField(default='Our Services', max_length=50)),
                ('button1_link', models.CharField(default='#services', max_length=200)),
                ('button2_text', models.CharField(default='Visit Us', max_length=50)),
                ('button2_link', models.CharField(default='#visit', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('tagline', models.CharField(blank=True, max_length=300, null=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('logo', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', help_text='Logo size: 400x400 pixels', keep_meta=True, null=True, quality=85, scale=None, size=[400, 400], upload_to='ministries/logos/')),
                ('banner_image', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', help_text='Banner size: 1200x600 pixels', keep_meta=True, quality=85, scale=None, size=[1200, 600], upload_to='ministries/banners/')),
                ('meeting_days', models.CharField(blank=True, max_length=100, null=True)),
                ('meeting_time', models.CharField(blank=True, max_length=100, null=True)),
                ('meeting_location', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('developing', 'Developing')], default='active', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_ministries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Ministries',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('service_type', models.CharField(choices=[('children', 'Children Service'), ('teenagers', 'Teenagers Service'), ('english', 'English Service'), ('swahili', 'Swahili Service'), ('youth', 'Youth Service'), ('prayer', 'Prayer Meeting'), ('bible_study', 'Bible Study'), ('men', "Men's Fellowship"), ('women', "Women's Fellowship")], max_length=20)),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('age_range', models.CharField(blank=True, max_length=50, null=True)),
                ('icon', models.CharField(default='fas fa-church', help_text='Font Awesome icon class', max_length=50)),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', help_text='Recommended size: 800x600 pixels', keep_meta=True, null=True, quality=85, scale=None, size=[800, 600], upload_to='services/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Service Time',
                'verbose_name_plural': 'Service Times',
                'ordering': ['day_of_week', 'start_time', 'order'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='VCCT Mbezi Beach', max_length=200)),
                ('site_logo', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', help_text='Logo size: 200x200 pixels', keep_meta=True, null=True, quality=85, scale=None, size=[200, 200], upload_to='config/')),
                ('site_favicon', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', help_text='Favicon size: 64x64 pixels', keep_meta=True, null=True, quality=85, scale=None, size=[64, 64], upload_to='config/')),
                ('hero_bg_image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', help_text='Hero background size: 1920x1080 pixels', keep_meta=True, null=True, quality=85, scale=None, size=[1920, 1080], upload_to='config/')),
                ('contact_email', models.EmailField(default='info@vcct.or.tz', max_length=254)),
                ('contact_phone', models.CharField(default='+255 762 441 719', max_length=20)),
                ('address', models.TextField(default='Mbezi Beach, Dar es Salaam')),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, null=True)),
                ('about_us', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('mission', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('vision', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('content', models.TextField()),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', help_text='Profile image size: 400x400 pixels', keep_meta=True, null=True, quality=85, scale=None, size=[400, 400], upload_to='testimonials/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('short_description', models.TextField(max_length=300)),
                ('event_type', models.CharField(choices=[('service', 'Church Service'), ('prayer', 'Prayer Meeting'), ('fellowship', 'Fellowship'), ('conference', 'Conference'), ('outreach', 'Outreach'), ('training', 'Training'), ('special', 'Special Event')], default='service', max_length=20)),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_date', models.DateField()),
                ('end_time', models.TimeField()),
                ('is_recurring', models.BooleanField(default=False)),
                ('location', models.CharField(max_length=200)),
                ('location_details', models.TextField(blank=True, null=True)),
                ('online_link', models.URLField(blank=True, null=True)),
                ('featured_image', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', help_text='Featured image size: 1200x800 pixels', keep_meta=True, quality=85, scale=None, size=[1200, 800], upload_to='events/')),
                ('requires_registration', models.BooleanField(default=False)),
                ('max_attendees', models.PositiveIntegerField(default=0)),
                ('registration_deadline', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.eventcategory')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='MinistryMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('leader', 'Leader'), ('assistant', 'Assistant Leader'), ('member', 'Member'), ('volunteer', 'Volunteer')], default='member', max_length=20)),
                ('joined_date', models.DateField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('ministry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.ministry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ministry_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('ministry', 'user')},
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('attended', 'Attended')], default='pending', max_length=20)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='core.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('event', 'email')},
            },
        ),
    ]
