# Generated by Django 4.2.8 on 2026-01-25 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='address',
            field=models.TextField(default='Vijana street SIDO Road, Moshi Kilimanjaro'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='contact_email',
            field=models.EmailField(default='info@tagkrt.or.tz', max_length=254),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='contact_phone',
            field=models.CharField(default='+255 784 344 079', max_length=20),
        ),
    ]
