# Generated by Django 4.2.8 on 2026-02-24 05:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_tithe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tithe',
            options={'ordering': ['-year', '-month', '-date_paid']},
        ),
        migrations.AddField(
            model_name='tithe',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_tithes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tithe',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('cancelled', 'Cancelled')], default='paid', max_length=20),
        ),
        migrations.AddIndex(
            model_name='tithe',
            index=models.Index(fields=['status'], name='core_tithe_status_90fec0_idx'),
        ),
        migrations.AddIndex(
            model_name='tithe',
            index=models.Index(fields=['date_paid'], name='core_tithe_date_pa_a8ac3c_idx'),
        ),
    ]
