# Generated by Django 4.2.8 on 2026-01-25 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=100)),
                ('level', models.PositiveIntegerField(choices=[(1, 'Founder / Baba wa Kiroho'), (2, 'Askofu / Senior Pastor'), (3, 'Mchungaji'), (4, 'Mzee wa Kanisa'), (5, 'Kiongozi wa Huduma')])),
                ('photo', models.ImageField(upload_to='leaders/')),
                ('vision_message', models.TextField(blank=True, null=True)),
                ('biography', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['level', 'order'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('church_branch', models.CharField(blank=True, max_length=100)),
                ('joined_at', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
